name: Docker publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs: # необязательные, позволяют указать параметры для запуска
      logLevel:
        description: 'Уровень логирования'
        required: false
        default: 'warning'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: 
            nodil1/Laba1
        tags: |
          type=semver,pattern={{version}}
          type=edge
        labels: |
          org.opencontainers.image.title=${{ github.repository }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.version=${{ github.ref }}
          org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
